<%
'This line gets added to other files
'<!-- #include file="language.asp" //-->

'These values can be changed in the custom\lang file
Dim   langBackToCommittee	
Dim   langCommittee		
Dim   langCommittees		
Dim   langNewCommittee		
Dim   langTabCommittees		
Dim   lanAdminCommittee		
Dim   lanRegisterCommitteeTitle 
Dim   langDiaplyCommittee	
Dim   langRegisterCommitteeTitle
Dim   langInsertCommittee2	
Dim   langInsertCommittee3	
Dim   langInsertCommittee4	
Dim   langAdminCommitteeAdded	
Dim   langAdminCommittee	
Dim   langDiaplyMember
Dim   langDiaplyContact
Dim   landBSCommittees
Dim   langBSCustomization

' Tab display text variables
Dim   langBSDocuments
Dim   langBSAddressBook		
Dim   langBSAnnouncements	
Dim   langBSCommittees		
Dim   langBSDiscussions		
Dim   langBSEventsCalendar	
Dim   langBSEvents	
Dim   langBSActionLine
Dim   langBSPayments
Dim   langBSFavorites		
Dim   langBSHome			
Dim   langBSLogin			
Dim   langBSMessages		
Dim   langBSMeetings		
Dim   langBSVoting
Dim   langBSAdmin      	
Dim   sProgramName

sProgramName          = Application("ProgramName")

langBSLogin			      = sProgramName & " Login"
langBSDocuments		    = sProgramName & " {Documents}"
langBSAddressBook		  = sProgramName & " {Address Book}"
langBSAnnouncements	  = sProgramName & " {Announcements}"
langBSCommittees		  = sProgramName & " {Directories}"
langBSDiscussions		  = sProgramName & " {Discussions}"
langBSEventsCalendar	= sProgramName & " {Event Calendar}"
langBSEvents			    = sProgramName & " {Events}"
langBSActionLine			    = sProgramName & " {Action Line}"
langBSPayments			    = sProgramName & " {Payments}"
langBSFavorites		    = sProgramName & " {Favorites}"
langBSHome			      = sProgramName & " {Home}"
langBSMessages		    = sProgramName & " {Messages}"
langBSMeetings		    = sProgramName & " {Meetings}"
langBSVoting          = sProgramName & " {Voting Polls}"	
langBSAdmin           = sProgramName & " {Admin}"
langBSCustomization   = sProgramName & " {Language Settings}"

'Language Constants
Const langAbstain			= "Abstain"
Const langAddDoc			= "Add Document"
Const langAddFolder			= "Add Folder"
Const langAddHelp			= "Add Help"
Const langAddToggle			= "Toggle Right-Click Menu"
Const langAgendaInfo		= "Agenda Information"
Const langAddAgenda			= "Add Agenda Information"
Const langAdmin				= "Admin"
Const langAlertSelect		= "Please select some blue text!"
Const langAll				= "All" 	' Context is Searching Users, Groups or All in address book
Const langAnnouncementLinks = "Announcement Links"
Const langAnnouncement		= "Announcement"
Const langAnnouncements		= "Announcements"
Const langApprovalRating	= "Approval Rating"
Const langBackTo        = "Back To"
Const langBackToSearch	= "Back To Search"
Const langBackToVotingPoll	= "Back To Voting Poll List"
Const langBackToCalendar	= "Back To Calendar"
      langBackToCommittee	= "Back To Directory List"
Const langBackToAnnouncementList	= "Back To Announcement List"
Const langBackToEventList	= "Back To Event List"
Const langBackToFavoriteList	= "Back To Favorite List"
Const langBackToGroupsList	= "Back To Board List"
'Const langBackToStart		= "Back To Start Page"
Const langBackToStart		= "Back"
Const langBackToTopic		= "Back To Topic"
Const langBackToTopicsList	= "Back To Topics List"
Const langCancel			= "Cancel"
Const langCc				= "Cc"
Const langClose     = "Close"
Const langChoose			= "Choose..."
Const langCollapseMenu		= "Collapse Menu"
      langCommittee			= "Committee"
      langCommittees		= "Committees"
Const langCompose			= "Compose"
Const langContact			= "Contact" 	'Context:  This is a user who is not a member, merely a contact
Const langConfirmDeleteDiscussion = "Performing this action will delete all topics and messages associated with this group.  Are you sure you want to proceed?"
Const langConfirmDeleteTopic = "Performing this action will also delete all messages associated with this topic.  Are you sure you want to proceed?"
Const langCopyright			= "Copyright &copy; 2006, <i>E-GovLink, inc.</i>  All Rights Reserved."
Const langCreate			= "Create"
Const langCreator			= "Creator"
Const langDate				= "Date"
Const langDateTime			= "Date/Time"
Const langDay1				= "Sun"
Const langDay2				= "Mon"
Const langDay3				= "Tue"
Const langDay4				= "Wed"
Const langDay5				= "Thu"
Const langDay6				= "Fri"
Const langDay7				= "Sat"
Const langDays				= "Days"
Const langDelete			= "Delete"
Const langDescription		= "Description"
Const langDetails			= "Details"
Const langDirectory			= "Directory"
Const langDirectoryLinks			= "Directory Links"
Const langDiscussion		= "Discussion"
Const langDiscussions		= "Discussions"
Const langDiscussionGroup	= "Discussion Board"
Const langDiscussionGroups	= "Discussion Boards"
Const langDiscussionLinks	= "Discussion Links"
Const langDocuments			= "Documents"
Const langDocumentsHome		= "Documents Home"
Const langDrafts			= "Drafts"
Const langDuration			= "Duration"
Const langEdit				= "Edit"
Const langEditAnnouncements = "List Announcements"
Const langEditEvents		= "List Events"
Const langEditFavorites		= "List Favorites"
Const langEditMembers		= "Edit Members"
Const langEditSecurity = "Edit Security"
Const langPersonalSettings = "Personal Settings"
Const langEditPersonalSettings = "Edit Personal Settings"
Const langEditPersonalSettingsDesc = "Manage your personal settings for this website."
Const langEntries			= "Entries"
Const langError       = "An Error Occurred"
Const langErrorSorry  = "We're sorry, but an error occurred while processing your request.<br>A message has been sent to support@eclink.com."
Const langErrorRetrievingTopic = "Error retrieving topic messages."
Const langEvent				= "Event"
Const langEventLinks		= "Event Links"
Const langEvents			= "Events"
Const langFavoriteLinks		= "Favorite Links"
Const langFavorites			= "Favorites"
Const langForgotPass		= "Forgot Your Password?"
Const langForward			= "Forward"
Const langFrom				= "From"
Const langGo				= "Go"
Const langGoBack			= "Go Back"
Const langGroup				= "Group"
Const langDiscussionBoard				= "Board"
Const langGroups			= "Groups"
Const langIn				= "in" 	'context:  Message 1 of 10 in discussion
Const langInbox				= "Inbox"
Const langInvalid			= "Invalid Username or Password"
Const langImage       = "Image"
Const langHours				= "Hours"
Const langLastReply			= "Last Reply"
Const langLocation			= "Location"
Const langLogMeAuto			= "Log me in automatically"
Const langLogIn				= "Log In"
Const langLogOut			= "Log Out"
Const langManageAccess = "Manage Folder Access"
Const langMember			= "Member"
Const langMembers     = "Members"
Const langMessage			= "Message"
Const langMessageBoxes		= "Message Boxes"
Const langMessageDeleted	= "Message has been deleted."
Const langMessageLinks		= "Message Links"
Const langMessages			= "Messages"
Const langMessageView		= "Message View"
Const langMinutes			= "Minutes"
Const langMonth01			= "January"
Const langMonth02			= "February"
Const langMonth03			= "March"
Const langMonth04			= "April"
Const langMonth05			= "May"
Const langMonth06			= "June"
Const langMonth07			= "July"
Const langMonth08			= "August"
Const langMonth09			= "September"
Const langMonth10			= "October"
Const langMonth11			= "November"
Const langMonth12			= "December"
Const langMore				= "More"
Const langName				= "Name"
Const langNeedsDiscussion	= "Needs Discussion"
Const langNew				= "New"
Const langNewAnnouncement	= "New Announcement"
      langNewCommittee		= "New Committee"
Const langNewContact		= "New Contact"
Const langNewDiscussion		= "New Discussion"
Const langNewDiscussionGroup = "New Board"
Const langNewDiscussions	= "New Discussions"
Const langNewEvent			= "New Event"
Const langNewFavorite		= "New Favorite"
Const langNewIssues			= "New Issues To Vote On"	'context:  You have 2 new issues to vote on.
Const langMeetingLinks		= "Meeting Links"
Const langNewMeeting		= "New Meeting"
Const langNewMeetings		= "New Meetings"
Const langNewMember			= "New User"
Const langNewMessage		= "New Message"
Const langNewMessages		= "New Messages"
Const langNewPoll			= "New Poll"
Const langNewTopic			= "New Topic"
Const langNewVote			= "New Vote"
Const langNewVotes			= "New Votes"
Const langNext				= "Next"
Const langNextMessage		= "Next Message"
Const langNextMonth			= "Next Month"
Const langNextPoll			= "Next Poll"
Const langNo				= "No"
Const langNoEntriesFound	= "No Entries Found"
Const langNoMeetingsFound	= "No new Meetings"
Const langNoDrafts			= "No message drafts."
Const langNoNewMessages	= "No new messages."
Const langNoSentMessages = "No sent messages."
Const langNoTopics			= "No topics for this discussion group."
Const langOf				    = "of" 	'context:  Message 1 of 10 in discussion
Const langOpen          = "Open"
Const langPassword			= "Password"
Const langPersonalFavorites = "Personal Favorites"
Const langPollSubject		= "Poll Subject"
Const langPrev				  = "Prev"
Const langPreviousMonth	= "Previous Month"
Const langPrevMessage		= "Prev Message"
Const langPrevPoll			= "Prev Poll"
Const langPrintCurrDoc  = "Print Current Document"
Const langPublish       = "Publish"
Const langPublished     = "Published"
Const langQuestion			= "Question"
Const langQuickLinks		= "Quick Links"
Const langRe				= "Re:"	'context:  Prefix to the subject of a reply
Const langFw                = "Fw:" 
Const langRecurrence		= "Recurrence"
Const langRefreshMenu		= "Refresh Menu"
Const langReplies			= "Replies"
Const langReply				= "Reply"
Const langReplyAll			= "Reply All"
Const langReplyToMessage	= "Reply To Message"
Const langResponses			= "Responses"
Const langSaveCurrDoc		= "Save Current Document"
Const langSearch        = "Search"
Const langSearchAddressBook = "Search Address Book"
Const langSearchDiscussions = "Search Discussions"
Const langSearchDocuments	= "Search Documents"
Const langSearchMessages	= "Search Messages"
Const langSendReply			= "Send Reply"
Const langSent				= "Sent"
Const langSentMail			= "Sent Mail"
Const langSentMessages		= "Sent Messages"
Const langStartTime			= "Start Time"
Const langStartedBy			= "Started By"
Const langStatus			= "Status"
Const langSubject			= "Subject"
Const langSubmitVote		= "Submit Vote"
Const langSubmitRegister	= "Register Now"
Const langSummary			= "Summary"
Const langTabAdmin		= "Admin"
      langTabCommittees		= "Committees"
Const langTabDiscussions	= "Discussions"
Const langTabDocuments		= "Documents"
Const langTabHome			= "Calendar"
Const langTabMeetings		= "Meetings"
Const langTabMessages		= "Messages"
Const langTabVoting			= "Voting"
Const langThereAre			= "There Are" 	'Context:  There Are 4 New Documents.
Const langThreadedView		= "Threaded View"
Const langTime				= "Time"
Const langTo				= "To"
Const langStockInformation = "Stock Information"
Const langTurnStockTickerOff = "Turn OFF Personal Stock Ticker."
Const langTurnStockTickerOn = "Turn ON Personal Stock Ticker."
Const langToggleStockTicker = "Toggle Stock Ticker"
Const langStockTickerOffNotice = "You are about to turn off your personal stock ticker.  If you proceed you may turn this feature back on under the Admin tab by clicking \'Toggle Stock Ticker\'.\n\nDo you wish to proceed?"
Const langTotal				= "Total"
Const langType				= "Type"
Const langTypeEmail			= "Email"
Const langTypeFTP			= "FTP Site"
Const langTypeNetwork		= "Network File"
Const langTypeWeb			= "Web Site"
Const langTypeSecure			= "Secure Web Site"
Const langTopicNewFirstMessage = "Topic: New (First Message)"
Const langUpdate			= "Update"
Const langUpdateAnnouncement = "Update Announcement"
Const langUpdateEvent		= "Update Event"
Const langUpdateFavorite	= "Update Favorite"
Const langUpdateRef			= "Update References"
Const langURL				= "URL"
Const langUser				= "User"
Const langUsers				= "Users"
Const langUserName			= "Username"
Const langAdminEditLang = "Edit Customizations"
Const langAdminCustomDescript = "Edit Language and/or Logo"
Const langVoted				= "Voted"
Const langVote        = "Vote"
Const langVoting			= "Voting"
Const langVotingLinks = "Voting Links"
Const langVotingPoll		= "Voting Poll"
Const langVoteType     = "Vote Type"
Const langVotingPollDetails = "Voting Poll Details"
Const langResponse = "Response"
Const langVotingPolls		= "Voting Polls"
Const langWeeks				= "Weeks"
Const langWelcomeBack		= "Welcome "
Const langViewDetails  = "View Details"
Const langYes				= "Yes"
Const langYouHave			= "You Have" 	'context:  You have x new messages
      lanAdminCommittee		= "Manage Committees"
      lanRegisterCommitteeTitle = "Register a new Committee"
	    langDiaplyMember		= "All Users"
 	    langDiaplyContact		= "All Contacts"
 	    langDiaplyRoles		= "All Roles"
 	    langDiaplyRole		= "All Roles"
      langDiaplyCommittee	= "Display Committees"
Const langContacts	= "Contacts"
Const langRole		= "Roles"
Const langJobTitle			= "Job Title"
      langRegisterCommitteeTitle= "Create a new committee"
Const langDepartment		= "Department"
Const langAddMeeting		= "Add Meeting Information"
Const langUpdateMeeting		= "Update Meeting Information"
Const langUpdateAgenda		= "Update Agenda Information"
Const langMeetingNew		= "Meeting: New"
Const langMeetingView		= "Meeting: View"
Const langMeetingChanges	= "Meeting: Changes"
Const langBack2MeetingsList = "Back To Meetings List"
Const langEnterEditGenInfo	= "Enter/Edit General Information"
Const langTopic				= "Topic"
Const langTopics			= "Topics"
Const langWhen				= "When"
Const langWhere				= "Where"
Const langReqBy				= "Requested By"
Const langHomeLinks			= "Home Links"
Const langAM				= "AM"
Const langPM				= "PM"
Const langAdminPermission   = "Manage the permissions"
Const langViewConfAtt		= "View Confirmed Attendees"
Const langEditMeeting		= "Edit Meeting"
Const langGeneralInfo		= "General Information"
Const langAgendaSort		= "Serial No"
Const langAgendaDesc		= "Agenda Description"
Const langAgendaSub			= "Agenda Subject"
Const langAdminLinks        = "Administrative Links"
Const langAdminTask			= "Task"
Const langAdminEditAnnounce = "Edit Announcements"
Const langAdminEditEvents   = "Edit Events"
Const langAdminEditFav      = "Edit Company Favorites"
Const langAdminEditPersonalFav      = "Edit Personal Favorites"
Const langAdminEditDoc      = "Edit Documents"
Const langAdminRegUser      = "New User"
Const langEditRegUser      = "Edit Profile"
Const langAdminRegDirectory = "New Directory"
Const langAdminRegContact   = "New Contact"
Const langAdminNoLinks      = "You must log on to use the administrative functions."
Const langAdminEditAnnounceDesc = "Add, Edit, or Delete announcements which appear on the home page."
Const langAdminEditEventsDesc = "Add, Edit, or Delete events which appear on the home page."
Const langAdminEditFavDesc  = "Add, Edit, or Delete Company favorites which appear on the home page."
Const langAdminEditPersonalFavDesc  = "Add, Edit, or Delete Personal favorites which appear on the home page."
Const langAdminEditDocDesc  = "Add, or Delete documents and folders in the documents section."
Const langAdminRegUserDesc  = "Create a new user for the site."
Const langEditRegUserDesc  = "Edit your personal user profile."
Const langAdminRegDirectoryDesc = "Create a new directory for the site."
Const langAdminRegContactDesc = "Create a new contact for the site."
Const langWelcomeGuest=			"Welcome Guest User!"
Const langDesignby=				"Powered by "
Const langNewAgenda			= "Meeting: New Agenda"
Const langUserInfo			="User Information"
Const langEditExtendedProperty="Edit/Add"
Const langNoDelete          = "No delete is made"
Const langTimeZone          = "Time Zone"

' DOCUMENT SECTION 
Const langEmptyDateSearch       = "No documents listed within the specified time period."
Const langEmptyTextSearch =  "Could not find any documents that meet that search criteria."
Const langDateSearchPrefixSingular = "There is"
Const langDateSearchPrefixPlural = "There are"
Const langDocument = "document"
Const langtoday = "today"
Const langSinceLastWeek = "since last week"
Const langSinceLast2Weeks = "since the last two weeks"
Const langSinceLastMonth = "since last month"
Const langAddedToday = "added today"
Const langAddedLastWeek = "added in the last week"
Const langAddedLastTwo = "added in the last 2 weeks"
Const langAddedLastMonth = "added in last month"
Const langViewNewDocs = "View new documents:"
Const langDocType = "Type"
Const langDocuName = "Document Name"
Const langDocuDateMade = "Date Created"

' DOCUMENT SECTION - (Add Catagory)
Const langChooseDestiny = "Choose a destination for your category"
Const langChooseCatName = "Choose a name for your category"
Const langAddCat = "Add the category"
Const langAddCatButton = "Add Category"
Const langAddHelpDoc ="Add Help Document"
Const langChooseTopicHelp = "Choose the topic for this help document"
Const langHelpTopic = "Help Topic:"
Const langChooseMethod = "Choose the method in which you will add the document"
Const langMethodOption = "Method:"
Const langMethodUpload = "Upload"
Const langMethodDirect = "Directly Add Content"
Const langDocuDefine = "Define your document"
Const langSelectFile = "Select File:"
Const langAddDocument = "Add Document"
Const langAddHelpDocument = "Add Help Document"
Const langDeleteAFolder = "Delete a Folder"
Const langChooseFolderDelete = "Choose a folder to delete"
Const langDeleteVerify = "Verify folder deletion"
Const langDeleteTheFolder = "Delete the folder"
Const langDeleteButton = "Delete Folder"
Const langAddDocument1 = "Add Document"
Const langDocDestiny = "Choose a destination for your document"
Const langCreateNewDOcIn ="Create new document in:"
Const langChooseDoc = "Choose one..."
Const langChooseDocMethod = "Choose the method in which you will add your document"
Const langDocMethod = "Method:"
Const langDocUpload = "Upload"
Const langDocDirect = "Directly Add Content"
Const langDocLink = "Create Link Only"
Const langDefineDoc = "Define your document"
Const langDocSelect = "Select File:"
Const langDocTitle = "Title: "
Const langDocContent = "Content: "
Const langDocHTML = "Is Content HTML?"
Const langDocURL = "URL: "
Const langDocNewWindow = "Open in new window"
Const langYourDocAdd = "Add your document"
Const langDocOverwrite = "Overwrite exisiting file"
Const langAgendaItems = "Agenda Items"
Const langNewAgendaItem = "New Agenda Item"

const langLoginBenefits = "Logging in will provide you with enhanced capabilites and preferences."
const langSendMsg = "Send Message"
const langSaveDraft = "Save Draft"
const langSentMailTop = "Messages: Sent Mail"
const langNewDocTop = "new"

'Used with timeout popup window
const langSessionTimeout = "Session Timeout"
const langOK             = "OK"
const langWillBeLoggedOff= "You will be logged off in 5 minutes due to inactivity.  Do you want to remain logged on?"
const langBeenLoggedOff  = "You have been logged off due to inactivity."

const langOriginalMessage= "Original Message"



%>
