<html>
<head>
  <title>Error</title>
  <link href="global.css" rel="stylesheet" type="text/css">
  <script language="Javascript">
  <!--
    function doLoad() {
      var s = parent.fraToc.hiddenframe.document.body.innerHTML.toUpperCase();

      pos = s.indexOf("PERMISSION DENIED")
      if (pos >= 0) {
        error.innerHTML = "<b>Permission Denied</b><br>Error generated by: <%= Request("path") %>";
      }
    }
  //-->
  </script>
</head>

<body bgcolor="#ffffff" onload="doLoad();">
  <font size="3"><b>Error</b></font>
  <hr style="height:1px;"><br>
  An error has occured within eCapture.
  <ul><li id="error" style="font-family:Tahoma,Sans-Serif,Arial; font-size:11px; color:#ff0000;"></li></ul>
  If you feel you should not have received this error, please contact your Administrator.
</body>
</html>