<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="WordPress/5.0.3" created="2019-03-08 14:26" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>Hamilton County Prosecutor</title>
	<link>http://hcpros.egovhost2.com</link>
	<description></description>
	<pubDate>Fri, 08 Mar 2019 14:26:24 +0000</pubDate>
	<language>en-US</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://egovhost2.com/</wp:base_site_url>
	<wp:base_blog_url>http://hcpros.egovhost2.com</wp:base_blog_url>


	<generator>https://wordpress.org/?v=5.0.3</generator>
<%

sSQL = "SELECT title ,offenses ,field_inmate_location_value ,field_inmate_id_value ,field_inmate_min_sentence_value ,field_inmate_max_sentence_value " _
      & " ,field_inmate_admitted_value ,field_inmate_date_next_eligible_value ,field_sex_offend_value ,field_inmate_description_value,CASE field_sex_offend_value WHEN '' THEN 'No' ELSE 'Yes' END as sexpred " _
      & " ,id as imgpostid " _
      & " FROM zhcprosinmatedata d " _
      & " LEFT JOIN zhcprosinmateimgs i ON i.post_title = d.field_inmate_id_value OR i.post_title + '00' = d.field_inmate_id_value " _
      & " WHERE 11 <= rowid " _
      & " ORDER BY rowid "

set oRs = Server.CreateObject("ADODB.Recordset")
oRs.Open sSQL, Application("DSN"), 3, 1
Do While Not oRs.EOF
	arrOff = split(oRs("offenses"),"|")
	statement = replace(replace(oRs("field_inmate_description_value"),"|",","),"##","""")
	if right(statement,2) = ">""" then statement = left(statement,len(statement)-1)
	if instr(statement,"""") = len(statement) then  statement = left(statement,len(statement)-1)

	'response.write oRs("title") & " - " & statement & "<hr />" & vbcrlf
	%>
	<item>
		<title><%=oRs("title") & " "%> <%=oRs("field_inmate_id_value")%></title>
		<link>http://hcpros.egovhost2.com/<%=replace(replace(trim(oRs("title"))," ","-"),".","")%>-<%=oRs("field_inmate_id_value")%>/</link>
		<pubDate>Thu, 07 Mar 2019 14:40:03 +0000</pubDate>
		<dc:creator><![CDATA[ecadmin]]></dc:creator>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_date><![CDATA[2019-03-12 11:55:03]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2019-03-12 11:55:03]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[closed]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[<%=replace(replace(trim(oRs("title"))," ","-"),".","")%>-<%=oRs("field_inmate_id_value")%>]]></wp:post_name>
		<wp:status><![CDATA[draft]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="category" nicename="pending-hearings"><![CDATA[Pending Hearings]]></category>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_edit_last]]></wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("imgpostid")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[name]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("title")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_name]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c81281ffb371]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[inmate_number]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("field_inmate_id_value")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_inmate_number]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812863fb373]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[sexual_predator]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("sexpred")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_sexual_predator]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812881fb374]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[location]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("field_inmate_location_value")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_location]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c8128b1fb375]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[offenses]]></wp:meta_key><%
				'DEAL WITH offenses
				i = -1
				strOff = ""
				for each item in arrOff
					i = i + 1
					offense = trim(item)
					offLen = len(offense)
					strOff = strOff & "i:" & i & ";s:" & offLen & ":""" & offense & """;"
				next
				'response.write "a:" & ubound(arrOff)+1 & ":{" & strOff & "}"
			%>
			<wp:meta_value><![CDATA[<%="a:" & ubound(arrOff)+1 & ":{" & strOff & "}"%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_offenses]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c81293bfb376]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[min_sentence]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("field_inmate_min_sentence_value")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_min_sentence]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812a10fb377]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[max_sentence]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=oRs("field_inmate_max_sentence_value")%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_max_sentence]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812a55fb378]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[date_admitted]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=year(oRs("field_inmate_admitted_value")) & addLeadingZero(month(oRs("field_inmate_admitted_value"))) & addLeadingZero(day(oRs("field_inmate_admitted_value")))%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_date_admitted]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812ab8fb379]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[next_eligibility_hearing_date]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=year(oRs("field_inmate_date_next_eligible_value")) & addLeadingZero(month(oRs("field_inmate_date_next_eligible_value"))) & addLeadingZero(day(oRs("field_inmate_date_next_eligible_value")))%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_next_eligibility_hearing_date]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812ad4fb37a]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[statement]]></wp:meta_key>
			<wp:meta_value><![CDATA[<%=statement%>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key><![CDATA[_statement]]></wp:meta_key>
			<wp:meta_value><![CDATA[field_5c812aeefb37b]]></wp:meta_value>
		</wp:postmeta>
	</item>
	<%
	
	oRs.MoveNext
loop
oRs.Close
Set oRs = Nothing

function addLeadingZero(value)
    addLeadingZero = value
    if value < 10 then
        addLeadingZero = "0" & value
    end if
end function
%>
</channel>
</rss>
